### ISSUE TITLE
No contexts, no hooks — very confused about this API

### ISSUE THREAD

**Issue by prometheas** [splitio/react-native-client#16]
I would have expected at least some of the basic components, from a `<SplitFactory />` root provider to `useTreatment()` hook. As it stands, this client library seems _purely_ declarative (and therefore very "un-React"). Am I missing something?

**Comment by EmilianoSanchez** [comment]
Hi @prometheas ,

Yes. As you can check in the public docs [here](https://help.split.io/hc/en-us/articles/4406066357901-React-Native-SDK), or type definitions [here](https://github.com/splitio/react-native-client/blob/main/types/index.d.ts), the React Native SDK has an imperative API, similar to our [JS SDK](https://help.split.io/hc/en-us/articles/360020448791-JavaScript-SDK) rather than our [React SDK](https://help.split.io/hc/en-us/articles/360038825091-React-SDK), which provides utilities based on React concepts and patterns like React components, high-order components and hooks.

The main goal of the RN SDK is to easily integrate in React Native and use the APIs provided by the React Native environment/library, rather than depending on alternative polyfill implementations.

Nevertheless, it's in our plans to provide a more React-like experience for our React Native package, probably relying on the current React SDK API that you're referencing.

**Comment by prometheas** [comment]
Alright. It simply looked like some sort of potential mistake. Closing out.
