### ISSUE TITLE
Calling `SplitFactory()` in any unit test results in unresolved async operations

### ISSUE THREAD

**Issue by prometheas** [splitio/react-native-client#20]
Calling `SplitFactory()` in my any unit test results in unresolved async operations, with the following output:

> Jest did not exit one second after the test run has completed.
>
> This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.

For what it's worth, I have [mocked](https://github.com/prometheas/split-react-native-jest-open-handles/blob/7c8529dddc3dd213e1c6f9580812b45c8fcaa46d/example.test.js#L1) the SplitFactory [as demonstrated](https://github.com/splitio/react-native-sdk-example/blob/master/ReactNativeExample/__tests__/App.test.js) in your example React Native app project, but this does not help.

I have created and shared a very bare React Native project that exemplifies the issue with only React Native, Jest, and this library. It can be found [here](https://github.com/prometheas/split-react-native-jest-open-handles). Please clone, install dependencies, and run `npx jest example.test.js` to see this outcome.

**Comment by EmilianoSanchez** [comment]
Hi @prometheas,

You need to "destroy" the SplitFactory instance in order to clean up resources, including some pending async operations executed be the SDK that are hanging your Jest test runner. 

In our example, the `App` component destroys the SDK [here](https://github.com/splitio/react-native-sdk-example/blob/master/ReactNativeExample/App.js#L80).

In your test code, you can try something like:
```
function initSplit() {
    return SplitFactory({
        core: {
            authorizationKey: 'localhost',
        },
        features: {},
        sync: {
            localhostMode: LocalhostFromObject(),
        },
    });
}

describe('test', () => {
    it('will fail to exit one second after test run has completed', () => {
        const factory = initSplit();
        factory.client().destroy();
    })
})
```

Thanks for sharing your issue. I will add a comment in the example regarding the `destroy` method in tests.

**Comment by prometheas** [comment]
Oh, interesting. Will give this a try and let you know how it worked out. Thanks.
